image_gallery/urls.py
from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = "gallery"
urlpatterns = [
    path("list/", views.GalleryListView.as_view(), name="image_list"),
    path("", views.GalleryListView.as_view(), name="image_list"),
    path('upload/', views.upload, name="upload"),
    path('<slug:date>/<slug:filename>/', views.upload_detail, name="image_details"),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

slaz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('image_gallery.urls')),
]

image_gallery/models.py
from django.db import models
import datetime
from . import utils

# Create your models here.
def calculate_reduction_factor(width):
    return (width / 512)

class Gallery(models.Model):
    title_text = models.CharField(max_length = 100)
    image_file = models.ImageField(upload_to = 'documents/%Y/%m/%d/', blank=False, null=False)
    upload_time = models.DateField(auto_now = True)
    
    class Meta:
        unique_together = ("title_text", 'upload_time')

image_gallery/forms.py
from django.forms import ModelForm
from . import models 

class GalleryForm(ModelForm):
    class Meta:
        model = models.Gallery
        fields = '__all__'

    def clean_title_text(self):
        title = self.cleaned_data['title_text']
        print("Got-title -> ", title)
        title = "-".join(title.split(" "))
        return title

image_gallery/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, Http404
from django.views.generic import DetailView, ListView
from django.utils.dateparse import parse_date

from . import models
from . import forms

from . import utils

from django.conf import settings

# Create your views here.
def upload(request):
    if request.method == "POST":
        print(request.FILES['image_file'])
        if request.FILES['image_file']:
            image_form = forms.GalleryForm(request.POST, request.FILES)
            if image_form.is_valid():
                image_obj = image_form.save()
                print("\033[31;1m" + str(image_obj.image_file.url) + "\033[0m")
                utils.compressImage(settings.BASE_DIR + image_obj.image_file.url)
        return HttpResponseRedirect(reverse("gallery:image_details", args=(str(image_obj.upload_time), str(image_obj.title_text)))) 
    else:
        print("GET METHOD LOADING POST...")
        image_form = forms.GalleryForm(label_suffix="")
        print(image_form)
        return render(request, 'image_gallery/upload.html', {"image_form": image_form})

def upload_detail(request, date, filename):
    # django model get 
    if type(date) != str:
        date = parse_date(date)
    image_object = None
    try:
        image_object = models.Gallery.objects.get(upload_time = date, title_text = filename)
    except models.Gallery.DoesNotExist:
        return Http404("Not Found")
    return render(request, 'image_gallery/upload_detail.html', {"image_object": image_object})

class GalleryListView(ListView):
    model = models.Gallery

image_gallery/templates/image_gallery/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'image_gallery/css/main.css' %}">
</head>
<body>
    <div class="heading">
    </div>
    <div class='nav_container'>
        <h1 class="title_app_name">Gallery</h1>
        {% block links %}
        {% endblock %}
    </div>
    {% block content %}
    {% endblock %}
    <div class="footer">
        <p>All Rights Reserved &copy; Kartik Verma. 2019</p>
    </div>
</body>
</html>

image_gallery/templates/image_gallery/gallery_list.html
{% extends 'image_gallery/base.html' %}
{% load static %}
{% block links %}
    <div class="links">
        <a href="{% url 'gallery:upload' %}">+</a>
    </div>
{% endblock %}

{% block content %} 
    {% if gallery_list %}
        <div class="gallery_container">
            <ul class="gallery_list">
                {% for item in gallery_list %}
                    <li class="gallery_item">
                        <a href="{% url 'gallery:image_details' item.upload_time item.title_text %}">
                            <img class="gallery_item_image" src="{{ item.image_file.url }}" />
                            <p class="gallery_item_title">{{ item.title_text }}</p>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div> 
    {% else %}
        <div class="center_content">
            <img src="{% static 'image_gallery/media/image_3.png' %}">
            <p>No Images Found</p>
        </div>         
    {% endif %}
{% endblock %}

image_gallery/templates/image_gallery/upload.html
{% extends 'image_gallery/base.html' %}
{% load static %}

{% block links %}
    <div class="links">
        <a href="{% url 'gallery:image_list' %}" class="link_list"><img src="{% static 'image_gallery/media/image_2.png' %}"></a>
    </div>
{% endblock %}

{% block content %}
    <div class="main_content">
        <div class="header">
            <p>Upload Image</p>
        </div>  
        <div class="image_form">
        {% if image_form %}
            <form method="POST" action="{% url 'gallery:upload' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ image_form.as_p }}
                <button type="submit">Submit</button>
            </form> 
        {% endif %}
        </div>
    </div>
{% endblock %}

image_gallery/templates/image_gallery/upload_detail.html
{% extends 'image_gallery/base.html' %}
{% load static %}
{% block links %}
    <div class="links">
        <a href="{% url 'gallery:upload' %}">+</a>
        <a href="{% url 'gallery:image_list' %}" class="link_list down_link"><img src="{% static 'image_gallery/media/image_2.png' %}"></a>
    </div>
{% endblock %}

{% block content %}
    <div class="main_content">
        {% if image_object %}
            <div>
                <img src="{{ image_object.image_file.url }}" class="image_act"/>
                <p class="image_title">{{ image_object.title_text }}</p> 
            </div>
        {% endif %}
    </div>
{% endblock %}